//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venda
    {
        public int IdVenda { get; set; }
        public System.DateTime DataVenda { get; set; }
        public decimal ValorNegociado { get; set; }
        public decimal ComissaoNegocio { get; set; }
        public int CasaVendavelIdCasaVendavel { get; set; }
        public int ClienteIdCliente { get; set; }
    
        public virtual CasaVendavel CasaVendavel { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
