//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasaArrendavel : Casa
    {
        public decimal ValorBaseMes { get; set; }
        public decimal Comissao { get; set; }
    
        public virtual Arrendamento Arrendamentos { get; set; }
    }
}
