//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrendamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arrendamento()
        {
            this.CasaArrendavel = new HashSet<CasaArrendavel>();
        }
    
        public int IdArrendamento { get; set; }
        public string InicioContrado { get; set; }
        public System.DateTime DuracaoMeses { get; set; }
        public string Renovavel { get; set; }
    
        public virtual Cliente Arrendatario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasaArrendavel> CasaArrendavel { get; set; }
    }
}
