//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limpeza
    {
        public int IdLimpeza { get; set; }
        public System.DateTime Data { get; set; }
        public int ServicoIdServico { get; set; }
        public int ServicoIdServico1 { get; set; }
    
        public virtual Servico Servicos { get; set; }
        public virtual Casa Casa { get; set; }
    }
}
